### ISSUE TITLE
System.IO.Exception after sending message

### ISSUE THREAD

**Issue by mikalovtch** [maritaria/SideKik#6]
I tried to use your example but got this erro after sending GetRoster or other message to kik serverr: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. Could you help me with solving it?

**Comment by maritaria** [comment]
I haven't worked on this project in forever, from your error description it seems the kik server closed the connection. This can have many reasons, if it happens directly at the start when logging in then they probably no longer support the client version we are spoofing, otherwise the protocol has updated and the library doesn't follow the new rules. Either way I don't want to work on this anymore so I'm afraid you will have to find help elsewhere. If you can't then you will have to reverse engineer the protocol yourself.

**Comment by mikalovtch** [comment]
> I haven't worked on this project in forever, from your error description it seems the kik server closed the connection. This can have many reasons, if it happens directly at the start when logging in then they probably no longer support the client version we are spoofing, otherwise the protocol has updated and the library doesn't follow the new rules. Either way I don't want to work on this anymore so I'm afraid you will have to find help elsewhere. If you can't then you will have to reverse engineer the protocol yourself.

It reads all incoming messages but stop doing it after sending message. Sometimes I get it working but I can't find any dependencies why it works this time but doesn't work next time. In any case thanks for your advice. 
Have a nice day
